### ISSUE TITLE
should not expose MIN macro

### ISSUE THREAD

**Issue by sthibaul** [simgrid/simgrid#274] opened 2018-06-26 10:37 UTC
/home/samy/recherche/gpu/starpu/examples/stencil/implicit-stencil.h:94:0: warning: "MIN" redefined
...
/usr/local/stow/simgrid-3.20/include/simgrid/msg.h:22:0: note: this is the location of the previous definition
 #define MIN(a, b) ((a) < (b) ? (a) : (b))

Exposing a MIN macro in the simgrid API is not a good thing to do :)

**Comment by mquinson** [comment] 2018-06-26 14:01
I'm affraid that fixing this one will bother our users currently relying on the fact that SimGrid is exposing that macro. I'm not sure whether we should prefer the API preservation or the API sanity.

Please note that we only define MIN if it's not existing already: https://github.com/simgrid/simgrid/blob/master/include/simgrid/msg.h#L21

Also, that's limited to MSG. These macro are not exposed in neither of SMPI, S4U or SimDAG.

**Comment by mquinson** [comment] 2018-06-29 07:06
Ok, I am closing this one, because MSG is the only impacted API and because the problem is not big enough to make us violate our beg to not change anything in MSG.
I hope you'll understand.

**Closed by mquinson** 2018-06-29 07:06 UTC
