### ISSUE TITLE
Java : autostart does not work

### ISSUE THREAD

**Issue by bcamus** [simgrid/simgrid#131] opened 2017-01-20 08:58 UTC
It seems that the auto-start feature does not work in Java.

Attached is a minimal example showing this point.

The output generated by the code is : 
[0.000000] [jmsg/INFO] Using regular java threads.
[adonis-1.grenoble.grid5000.fr:energy VM runner:(1) 0.000000] [jmsg/INFO] starting a dummy process on graphene-1.nancy.grid5000.fr
[graphene-1.nancy.grid5000.fr:dummy:(2) 0.000000] [jmsg/INFO] I start
[adonis-1.grenoble.grid5000.fr:energy VM runner:(1) 50.000000] [jmsg/INFO] powering off graphene-1.nancy.grid5000.fr
[adonis-1.grenoble.grid5000.fr:energy VM runner:(1) 60.000000] [jmsg/INFO] powering on graphene-1.nancy.grid5000.fr
[260.000000] [jmsg/INFO] MSG_main finished; Cleaning up the simulation...

The awaited output is : 
[0.000000] [jmsg/INFO] Using regular java threads.
[adonis-1.grenoble.grid5000.fr:energy VM runner:(1) 0.000000] [jmsg/INFO] starting a dummy process on graphene-1.nancy.grid5000.fr
[graphene-1.nancy.grid5000.fr:dummy:(2) 0.000000] [jmsg/INFO] I start
[adonis-1.grenoble.grid5000.fr:energy VM runner:(1) 50.000000] [jmsg/INFO] powering off graphene-1.nancy.grid5000.fr
[adonis-1.grenoble.grid5000.fr:energy VM runner:(1) 60.000000] [jmsg/INFO] powering on graphene-1.nancy.grid5000.fr
[graphene-1.nancy.grid5000.fr:dummy:(3) 60.000000] [jmsg/INFO] I start
[graphene-1.nancy.grid5000.fr:dummy:(3) 260.000000] [jmsg/INFO] I'm done
[260.000000] [jmsg/INFO] MSG_main finished; Cleaning up the simulation...

[SimGrid-BugReport-Autostart.zip](https://github.com/simgrid/simgrid/files/717076/SimGrid-BugReport-Autostart.zip)

**Comment by frs69wq** [comment] 2018-01-19 12:27
This bug is not specific to Java. An equivalent code in S4U does reproduce the bug. According to the debug information, the call to setAutoRestart() correctly adds the process to the list of processes to restart when the host is turned back on. However, the actual restart is never done.
I try several things but none work:
 + explicitly calling SIMIX_host_restart(host) in turnOn()
 + add the host to the hosts_that_restart vector before turning it back on (in that case SIMIX_host_restart is called but much too late, in the next scheduling round at time 260)

These two solutions restart the process but segfautlt with a cryptic backtrace:

[Fafard:Dummy:(3) 62.000000] src/xbt/exception.cpp:49: [xbt_exception/CRITICAL] Uncaught exception std::bad_function_call: bad_function_call
[Fafard:Dummy:(3) 62.000000] src/xbt/exception.cpp:86: [xbt_exception/CRITICAL] Current backtrace:
[Fafard:Dummy:(3) 62.000000] src/xbt/exception.cpp:88: [xbt_exception/CRITICAL]   -> simgrid::xbt::backtrace() at ././src/xbt/backtrace.cpp:91, 0x52f3213
[Fafard:Dummy:(3) 62.000000] src/xbt/exception.cpp:88: [xbt_exception/CRITICAL]   -> simgrid::xbt::handler() at ././src/xbt/exception.cpp:105, 0x530eea2
[Fafard:Dummy:(3) 62.000000] src/xbt/exception.cpp:88: [xbt_exception/CRITICAL]   -> std::rethrow_exception(std::__exception_ptr::exception_ptr) at ??:?, 0x59056b5
[Fafard:Dummy:(3) 62.000000] src/xbt/exception.cpp:88: [xbt_exception/CRITICAL]   -> std::terminate() at ??:?, 0x5905700
[Fafard:Dummy:(3) 62.000000] src/xbt/exception.cpp:88: [xbt_exception/CRITICAL]   -> __cxa_throw at ??:?, 0x5905918
[Fafard:Dummy:(3) 62.000000] src/xbt/exception.cpp:88: [xbt_exception/CRITICAL]   -> simgrid::xbt::Task<void ()>::operator()() at ./teshsuite/s4u/./include/xbt/functional.hpp:267, 0x40a355
[Fafard:Dummy:(3) 62.000000] src/xbt/exception.cpp:88: [xbt_exception/CRITICAL]   -> std::function<void ()> simgrid::s4u::Actor::wrap_task<void (*)()>(void (*)())::{lambda()#1}::operator()() const at ./teshsuite/s4u/./include/simgrid/s4u/Actor.hpp:147, 0x409fae
[Fafard:Dummy:(3) 62.000000] src/xbt/exception.cpp:88: [xbt_exception/CRITICAL]   -> std::_Function_handler<void (), std::function<void ()> simgrid::s4u::Actor::wrap_task<void (*)()>(void (*)())::{lambda()#1}>::_M_invoke(std::_Any_data const&) at /usr/include/c++/5/functional:1871, 0x40a962
[Fafard:Dummy:(3) 62.000000] src/xbt/exception.cpp:88: [xbt_exception/CRITICAL]   -> std::function<void ()>::operator()() const at /usr/include/c++/5/functional:2267, 0x51d264d

I think this is because the process is killed AND destroyed when the host is turned off, but don't know to fix this:

[Fafard:Dummy:(2) 50.000000] [simix_process/DEBUG] Control returned to me: 'Dummy'
[Fafard:Dummy:(2) 50.000000] [simix_process/DEBUG] I wanna die!
[Fafard:Dummy:(2) 50.000000] [simix_host/DEBUG] Push host Fafard to watched_hosts because state == SURF_RESOURCE_OFF
[Fafard:Dummy:(2) 50.000000] [simix_host/DEBUG] Adding Process Dummy to the auto-restart list of Host Fafard
[Fafard:Dummy:(2) 50.000000] [simix_process/DEBUG] Process Dummy@Fafard is dead
[Fafard:Dummy:(2) 50.000000] [simix_process/DEBUG] Cleanup process Dummy (0x78b6370), waiting synchro (nil)
[Fafard:Dummy:(2) 50.000000] [simix_process/DEBUG] 0x78b6370 should not be run anymore
[Fafard:Dummy:(2) 50.000000] [simix_process/DEBUG] Yield actor 'Dummy'
[50.000000] [simix_process/DEBUG] Cleanup process Dummy (0x78b6370), waiting synchro (nil)
[50.000000] [simix_process/DEBUG] 0x78b6370 should not be run anymore
[60.000000] [simix_process/DEBUG] Getting rid of 0x78b6370

**Comment by frs69wq** [comment] 2018-07-20 07:50
Closed by d53e30e

**Comment by frs69wq** [comment] 2018-08-15 00:45
This time really closed by 01b1b51

**Closed by frs69wq** 2018-08-15 00:45 UTC
Labels: bug, java, s4u

**Comment by mquinson** [comment] 2018-08-15 08:16
@bcamus could you please check that this issue is really fixed for you? I'd be really surprised if not, but I think we didn't check on Java yet.
