### ISSUE TITLE
Problem creating mailbox from multiple hosts

### ISSUE THREAD

**Issue by edelpozop** [simgrid/simgrid#391] opened 2024-01-15 07:42 UTC
I am using the latest version of SimGrid where I have a platform with a cluster of 1000 hosts and for each one I want to create 1000 mailboxes. However, when I run it, out of those 1000 hosts, there are approximately 60 hosts whose mailbox is not created, and if I want to send information to those hosts, the program gives segment violation. I have tried with previous versions and there are still problems with mailbox creation. I have checked that those mailboxes that are not created with the sg_maiblox_by_name function the length is 0, while the remaining 900 are created.

**Comment by mpoquet** [comment] 2024-01-15 09:25
Hi! Can you provide us a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) so we can try to reproduce the issue?

**Comment by adegomme** [comment] 2024-01-15 09:37
This is a duplicate of https://framagit.org/simgrid/simgrid/-/issues/119 which has the reproducing files
It was posted at the right place, there is no need to duplicate it here. It can take some time to get a response, please be patient

**Comment by edelpozop** [comment] 2024-01-15 09:40
I apologize, I was not sure if I had to ask it also in Github

**Comment by agiersch** [comment] 2024-01-15 11:05
See comment on framagit.

**Closed by agiersch** 2024-01-15 11:05 UTC
