### ISSUE TITLE
Seg fault on Disk interface coupled with clustered platform

### ISSUE THREAD

**Issue by Nivekiba** [simgrid/simgrid#383] opened 2023-02-08 15:04 UTC
Good morning everyone,
I try to deploy 20 nodes using the cluster tag in xml platform and i try to create disk for each host in the python application but i got segfault. I tested individually the disk interface (for read and write async) and the cluster creation  and both are working well separately but when i combine the 2, i got Segmentation fault and don't know why.

There is the `platform.xml` file:
```
<?xml version='1.0'?>
<!DOCTYPE platform SYSTEM "https://simgrid.org/simgrid.dtd">
<platform version="4.1">
  <zone id="world" routing="Full">
    <cluster id="cluster-crossbar"
             prefix="node-" radical="0-20" suffix="-cluster"
	     speed="10Gf" bw="125MBps" lat="50us"/>
  </zone>
</platform>
```
Simple

Here is the `deployment.xml` file
```
<?xml version='1.0'?>
<!DOCTYPE platform SYSTEM "https://simgrid.org/simgrid.dtd">
<platform version="4.1">
  <!-- The master actor (with some arguments) -->
  <actor host="node-0-cluster" function="activity">
    <argument value="20"/>        <!-- Number of tasks -->
  </actor>
  <!-- The worker actors (with no argument) -->
  <actor host="node-1-cluster" function="activity" />
</platform>
```
`node-0-cluster` and `node-1-cluster` successfully generated by the cluster in platform.xml (I test it)

And here is the app `app.py` For now there is nothing because i have seg fault now like i said before:
```
import sys
from simgrid import Engine, Host, this_actor, Disk

def activity(*args):
    this_actor.info(f"Args: {args} !!")
    this_actor.info(f"disks => {Host.current()}")
    
    for d in Host.current().get_disks():
        task = d.write_async(10000) <= segfault here
        task.wait()


if __name__ == '__main__':

    e = Engine(sys.argv)

    # Register the classes representing the actors
    e.register_actor("activity", activity)

    # Load the platform description and then deploy the application
    e.load_platform(sys.argv[1])

    for h in e.get_all_hosts():
        h.create_disk("disk1", "240MBps", "170MBps")

    e.get_netzone_root().seal()
    
    e.load_deployment(sys.argv[2])

    # Run the simulation
    e.run()

    this_actor.info("Simulation is over")
```

I tried the `seal` from the netzone_root because i saw it in an python example provided by simgrid but it doesn't change anything.
It will be so nice if someone can help me and say what i'm doing wrong or not.

Best regards.

**Comment by agiersch** [comment] 2023-02-08 16:35
Hi,

Thanks for the report.
It seems to work if you call `seal()` for each new disk:
```
    for h in e.get_all_hosts():
        h.create_disk("disk1", "240MBps", "170MBps").seal()
```

IIUC, this is because the hosts are already sealed when then platform file is loaded.

I'm not sure if it's the expected behavior or if it's a bug. Maybe @mquinson or @frs69wq can tell?

BTW `e.get_netzone_root().seal()` is not mandatory here (it's called automatically by `e.run()`).

Regards,

**Comment by Nivekiba** [comment] 2023-02-09 09:29
Ah well thanks for your response @agiersch. It's working.
I guess we will wait for @mquinson or @frs69wq to tell if it's the expected behavior.

Meanwhile, i'm going to continue with this for now.

**Comment by mquinson** [comment] 2023-02-15 15:51
Hello, we just discussed with @frs69wq and we commited a fix for this bug. Thanks for reporting!

**Closed** 2023-02-15 23:56 UTC
