### ISSUE TITLE
run hpl with np 1008 failed in simgrid with log “Cannot allocate memory”

### ISSUE THREAD

**Issue by Qinghe12** [simgrid/simgrid#375] opened 2021-04-16 09:27 UTC
Env info : 
hpl ： Optimized HPL code for SimGrid https://github.com/Ezibenroc/hpl
simgrid：version 3.27
docker：version 18.03.1-ce, build 9ee9f40
OS:CentOS Linux 7
kernel：linux 4.19.56
DDR ：380GB

 We ran hpl with np 1008 in simgrid with cmdline : 

simgrid@e8feeca8173a #   ./smpirun -np 1008     --cfg=smpi/privatization:dlopen     --cfg=smpi/display-timing:yes --cfg=smpi/display-allocs:yes          --cfg=smpi/shared-malloc-blocksize:536870912     -hostfile $PLATFORM_DIR/hostfiles/hostfile_144.txt     -platform $PLATFORM_DIR/reference_point/crossbar_144nodes.xml  ./xhpl

**error occurred  with log  as following when memory real  consumption reached 50GB：**

[node] #    ./src/smpi/internals/smpi_shared.cpp:242: [root/CRITICAL] Could not map folded virtual memory (Cannot allocate memory). Do you perhaps need to increase the size   of the mapped file using --cfg=smpi/shared-malloc-blocksize:newvalue (default 1048576) ? You can also try using  the sysctl vm.max_map_count. If you are using huge pages, check that you have a     t least one huge page (/proc/sys/vm/nr_hugepages) and that the directory you are passing is mounted correctly (mount /path/to/huge -t hugetlbfs -o rw,mode=0777).
Backtrace (displayed in actor 41)

Is there any config wrong or other missing ？

**Comment by adegomme** [comment] 2021-04-16 10:09
hello,
did you do anything the error message asked you to try ?

**Comment by Ezibenroc** [comment] 2021-04-16 10:18
Could you also tell us:
- The commit you used for the HPL repository.
- How you compiled HPL code.
- What parameters you used in the HPL configuration file (notably the matrix size).

**Comment by Qinghe12** [comment] 2021-04-17 05:50
@adegomme  , Increasing smpi/ shared-malloc-blocksize by 4 times can solve this.
It seems that there are some memory leaks  in final log as following：

[smpi_utils/INFO] Simulated time: 4.59633e+06 seconds.
The simulation took 11303.2 seconds (after parsing and platform setup)
4442.73 seconds were actual computation of the application
[4596332.566633] [smpi_utils/INFO] Probable memory leaks in your code: SMPI detected 6047 unfreed MPI handles : display types and addresses (n max) with --cfg=smpi/list-leaks:n.
Running smpirun with -wrapper "valgrind --leak-check=full" can provide more information
[4596332.566633] [smpi_utils/INFO] Memory Usage: Simulated application allocated 93308259072 bytes during its lifetime through malloc/calloc calls.
Largest allocation at once from a single process was 11616 bytes, at HPL_pdpanel_init.c:407. It was called 7875504 times during the whole simulation.
If this is too much, consider sharing allocations for computation buffers.
This can be done automatically by setting --cfg=smpi/auto-shared-malloc-thresh to the minimum size wanted size (this can alter execution if data content is necessary)

**Comment by Ezibenroc** [comment] 2021-04-17 08:26
If you compiled HPL with the compilation variable `SMPI_OPTIMIZATION_LEVEL` greater or equal to 4, this is expected. We modified HPL to reuse some internal data structures (called panels) from one iteration to another, to reduce the number of allocations. See the file [HPL_pdpanel_init.c](https://github.com/Ezibenroc/hpl/blob/09f8d53fc5b72bbaad3c99a6f976323004a8b606/src/panel/HPL_pdpanel_init.c#L61-L203) for the details.
We did not implement the deallocation of these reused panels as it was not strictly needed, the number of allocations is bounded, and we could only free them at the very end of the simulation, to be sure that they are not needed anymore.
On the other hand, I agree that this "memory leak detected" message is not pleasant, I might fix it.

This being said, I do not expect these "memory leaks" to be the cause of your high memory consumption.

**Comment by adegomme** [comment] 2021-04-17 10:09
Be careful, the memory usage you saw may be a false positive. The HPL version using shared memory in SMPI only uses the same physical memory segment over and over, but tools such as htop may still report it as  real memory usage. We run the 144 process version on ci systems with less than 2GB or ram without issue or swapping. And htop and others will report that the process takes 3.6GB.

**Comment by adegomme** [comment] 2021-04-17 10:50
And for the memory usage, I notice that your final message says : 
Largest allocation at once from a single process was 11616 bytes, at HPL_pdpanel_init.c:407. It was called 7875504 times during the whole simulation.

Line is a bit odd, I think the allocation is just before (l403). 

But these are only accounted if actual malloc are used, not shared mallocs.  So it seems you did not compile with SMPI_OPTIMIZATION_LEVEL >=3, indeed, and this is turned into a simple malloc (more actual memory usage to expect)
see: 
https://github.com/Ezibenroc/hpl/blob/master/src/panel/HPL_pdpanel_init.c#L195
where the redefinition is done

#define smpi_partial_malloc(size, start_private, stop_private) malloc(size)

**Comment by mquinson** [comment] 2021-07-12 23:57
Hello @Qinghe12, since you reported that changing a parameter solved the issue, do you think that we can close the report, or is there anything that we still need to fix before closing it?

Thanks for reporting,
Mt

**Comment by mquinson** [comment] 2022-02-23 23:58
Closing now as it seems that everything is now working.

Thanks for reporting, feel free to reopen on need.

**Closed by mquinson** 2022-02-23 23:58 UTC
Labels: smpi, moreinfo
