### ISSUE TITLE
Hosts and Links failures don't work in the Java world

### ISSUE THREAD

**Issue by kenenbek** [simgrid/simgrid#75] opened 2016-04-18 19:46 UTC
This issue is described here on [stackoverflow](http://stackoverflow.com/questions/36679338/simgrid-model-abnormal-situations).
I relied on this [example](https://github.com/mquinson/simgrid/tree/master/examples/java/app/masterworker). In example/platform.xml I added to Sirois host attribute state_file="trace/sirois.fail" with content:
PERIODICITY 10.0
1.0 1
2.0 0
And it gives me an error:

```
** SimGrid: UNCAUGHT EXCEPTION received on java(11): category: action canceled; value: 0
** 
** Thrown by masterslave.Slave() in this process
[Sirois:masterslave.Slave:(11) 2.000000] /builds/workspace/SimGrid-Multi/build_mode/Debug/node/simgrid-debian-wheezy-64/build/SimGrid-3.12/src/xbt/ex.c:148: [xbt_ex/CRITICAL] 

**   In smx_ctx_java_stop() at ??:?
**   In SIMIX_process_on_exit() at ??:?
**   In simcall_comm_recv() at ??:?
**   In MSG_mailbox_get_task_ext_bounded() at ??:?
**   In MSG_task_receive_ext() at ??:?
**   In Java_org_simgrid_msg_Task_receive() at ??:?
**   In ?? at [0x7fe1e1012d98]
```

P.S This issue was approved by @mquinson

**Comment by mquinson** [comment] 2016-04-19 20:44
I cannot reproduce the problem. If I attach another trace to another host, the exception seems properly catched. If I attach that very trace to that very host, it does not change anything because that host does not seem to be used at all.

Could you please do a zipfile with the java classes that you used, the deployment file and the platform file (no matter how light the changes are, include these files).

**Comment by kenenbek** [comment] 2016-04-19 21:00
2016-04-19 23:44 GMT+03:00 Martin Quinson <notifications@github.com>:

**Comment by kenenbek** [comment] 2016-04-19 21:02
https://drive.google.com/file/d/0B7mcyGJKuGE2aHE4emVNUTgtNXRhLXZaSE9Xa3JoWVd1cEk4/view?usp=sharing

**Comment by mquinson** [comment] 2016-04-19 22:30
I had to update your platform files that were intended for the last stable version instead of the current one, but beside of this, your code works rather well:

```
mquinson@nouzonket:/tmp/toto/async$ ~/Code/simgrid/tools/simgrid_update_xml.pl platform.xml 
platform.xml was using version 3
mquinson@nouzonket:/tmp/toto/async$ ~/Code/simgrid/tools/simgrid_update_xml.pl asyncDeployment.xml 
mquinson@nouzonket:/tmp/toto/async$ cd ..
mquinson@nouzonket:/tmp/toto$ java -cp ~/Code/simgrid/simgrid.jar:. async.AsyncTest async/platform.xml async/asyncDeployment.xml [0.000000] [jmsg/INFO] Using regular java threads.
[Jacquelin:async.Master:(1) 0.000000] [jmsg/INFO] Hello! Got 7 slaves and 5 tasks to process
[Jacquelin:async.Master:(1) 0.000000] [jmsg/INFO] Sending "Task_0" to "slave_0"
[Jackson:async.Forwarder:(2) 0.000000] [jmsg/INFO] Receiving on 'slave_0'
[Casavant:async.Forwarder:(3) 0.000000] [jmsg/INFO] Receiving on 'slave_1'
[iRMX:async.Slave:(4) 0.000000] [jmsg/INFO] Receiving on 'slave_2'
[Bousquet:async.Slave:(5) 0.000000] [jmsg/INFO] Receiving on 'slave_3'
[Soucy:async.Slave:(6) 0.000000] [jmsg/INFO] Receiving on 'slave_4'
[Kuenning:async.Slave:(7) 0.000000] [jmsg/INFO] Receiving on 'slave_5'
[Browne:async.Slave:(8) 0.000000] [jmsg/INFO] Receiving on 'slave_6'
[Stephen:async.Slave:(9) 0.000000] [jmsg/INFO] Receiving on 'slave_7'
[Robert:async.Slave:(10) 0.000000] [jmsg/INFO] Receiving on 'slave_8'
[Sirois:async.Slave:(11) 0.000000] [jmsg/INFO] Receiving on 'slave_9'
[Monique:async.Slave:(12) 0.000000] [jmsg/INFO] Receiving on 'slave_10'
[Jacquelin:async.Master:(1) 0.000000] [jmsg/INFO] Sending "Task_1" to "slave_1"
[Jacquelin:async.Master:(1) 0.000000] [jmsg/INFO] Sending "Task_2" to "slave_2"
[Jacquelin:async.Master:(1) 0.000000] [jmsg/INFO] Sending "Task_3" to "slave_3"
[Jacquelin:async.Master:(1) 0.000000] [jmsg/INFO] Sending "Task_4" to "slave_4"
[Jackson:async.Forwarder:(2) 0.851467] [jmsg/INFO] Sending "Task_0" to "slave_7"
[Casavant:async.Forwarder:(3) 1.357014] [jmsg/INFO] Sending "Task_1" to "slave_9"
[Bousquet:async.Slave:(5) 2.000000] [jmsg/INFO] Received a task
[Bousquet:async.Slave:(5) 2.000000] [jmsg/INFO] Received "Task_3". Processing it.
[Soucy:async.Slave:(6) 2.000000] [jmsg/INFO] Received a task
[Soucy:async.Slave:(6) 2.000000] [jmsg/INFO] Received "Task_4". Processing it.
[Soucy:async.Slave:(6) 2.000364] [jmsg/INFO] Receiving on 'slave_4'
[Bousquet:async.Slave:(5) 2.001165] [jmsg/INFO] Receiving on 'slave_3'
[Stephen:async.Slave:(9) 4.000000] [jmsg/INFO] Received a task
[Stephen:async.Slave:(9) 4.000000] [jmsg/INFO] Received "Task_0". Processing it.
[iRMX:async.Slave:(4) 4.000000] [jmsg/INFO] Received a task
[iRMX:async.Slave:(4) 4.000000] [jmsg/INFO] Received "Task_2". Processing it.
[Stephen:async.Slave:(9) 4.000728] [jmsg/INFO] Receiving on 'slave_7'
[iRMX:async.Slave:(4) 4.000728] [jmsg/INFO] Receiving on 'slave_2'
[Jacquelin:async.Master:(1) 5.000000] [jmsg/INFO] All tasks have been dispatched. Let's tell (asynchronously) everybody the computation is over, and sleep 20s so that nobody gets a message from a terminated process.
[Jackson:async.Forwarder:(2) 5.851463] [jmsg/INFO] Got a finalize task. Let's forward (asynchronously) that we're done, and then sleep 20 seconds so that nobody gets a message from a terminated process.
[Kuenning:async.Slave:(7) 6.000000] [jmsg/INFO] Received Finalize. I'm done. See you!
[Browne:async.Slave:(8) 6.000000] [jmsg/INFO] Received Finalize. I'm done. See you!
[Casavant:async.Forwarder:(3) 6.357007] [jmsg/INFO] Got a finalize task. Let's forward (asynchronously) that we're done, and then sleep 20 seconds so that nobody gets a message from a terminated process.
[Soucy:async.Slave:(6) 7.000364] [jmsg/INFO] Received Finalize. I'm done. See you!
[Bousquet:async.Slave:(5) 7.001165] [jmsg/INFO] Received Finalize. I'm done. See you!
[Monique:async.Slave:(12) 8.000000] [jmsg/INFO] Received Finalize. I'm done. See you!
[Robert:async.Slave:(10) 9.000000] [jmsg/INFO] Received Finalize. I'm done. See you!
[iRMX:async.Slave:(4) 9.000728] [jmsg/INFO] Received Finalize. I'm done. See you!
[Stephen:async.Slave:(9) 9.000728] [jmsg/INFO] Received Finalize. I'm done. See you!
[25.000000] [simix_kernel/INFO] Restart processes on host: Sirois
[25.000000] [simix_kernel/INFO] Restart processes on host: Sirois
[Jacquelin:async.Master:(1) 25.000000] [jmsg/INFO] Goodbye now!
[Jackson:async.Forwarder:(2) 25.851463] [jmsg/INFO] I'm done. See you!
[Casavant:async.Forwarder:(3) 26.357007] [jmsg/INFO] I'm done. See you!
[29.000728] [jmsg/INFO] MSG_main finished; Cleaning up the simulation...
mquinson@nouzonket:/tmp/toto$ 
```

This seems rather OK to me :)

**Comment by kenenbek** [comment] 2016-04-20 00:29
I added incorrect link. This package with "failure" error. 
 https://drive.google.com/file/d/0B7mcyGJKuGE2WWRsbF8zdE80bnc/view?usp=sharing

**Comment by mquinson** [comment] 2016-04-20 06:11
It is still not usable with the latest simgrid.jar, since the xml is not uptodate. Are you sure that this is the right version that you intended to send?

**Comment by kenenbek** [comment] 2016-04-20 07:47
Hmm, but platform.xml and asyncDeployment is updated by
simgrid_update_xml.pl.

**Comment by mquinson** [comment] 2016-04-20 12:26
you have 2 deploy files in your second archive, and I was using the wrong one. Ok, I can reproduce the issue, I'll look at it.

**Comment by mquinson** [comment] 2016-04-21 11:41
Bad news. This is not a simple task that I can do during lunch time, to just fix a simple typo that someone did, or simply cover another code path that got forgotten when the feature of host failure was added to Java.
Because that feature was never added to Java. I would have to implement this completely, and this is not something that I can currently do. 

We are lacking the manpower on the project to address this issue in a timely manner. I am deeply sorry.

**Comment by anaderi** [comment] 2016-04-21 13:51
@mquinson , are there any workarounds to model failures?

**Comment by frs69wq** [comment] 2016-04-21 13:56
A possible workaround is to go for the C/C++ version where everything is correctly handled, as it is the native language of SimGrid. The present issue is related to the bindings from C to Java that are unfortunately incomplete.

**Comment by mquinson** [comment] 2016-04-21 17:03
We could hint about how to implement this, but I cannot promise that this will be an easy task. It shouldn't be too hard. Someone relatively fluent in C should read http://simgrid.gforge.inria.fr/simgrid/3.13/doc/group__XBT__ex.html and protect the MSG calls in https://github.com/mquinson/simgrid/blob/master/src/bindings/java/jmsg_task.cpp 

You want to throw a java exception when an C exception is received, with one of the jxbt_throw_* existing in https://github.com/mquinson/simgrid/blob/master/src/bindings/java/jxbt_utilities.h

In the case pointed by @kenenbek, the exception kills the simulation in the receive function, but the send function will probably have to be protected too. If you use other functions (such as asynchronous comms), then you'll have to protect them too.

**Comment by agiersch** [comment] 2019-11-05 09:58
I can't reproduce this issue. It it has certainly been fixed in the meantime.
Closing.

**Closed by agiersch** 2019-11-05 09:58 UTC
Labels: java
