### ISSUE TITLE
Segmentation fault when using a multilink routes in the platform with compound host model - SimDag

### ISSUE THREAD

**Issue by AOA-Mohammed** [simgrid/simgrid#262] opened 2018-04-11 08:52 UTC
I studying different scheduling techniques using SimDag. I represented my system in the platform file. I used the links as switches as in the example in http://simgrid.gforge.inria.fr/simgrid/3.18/doc/examples.html

I configured the platform to use the compound model, because I want to use a more realistic network model (IB or SMPI)

I get a segmentation fault from the simulator when the simulation trying to execute an end to end communication task on a multilink route in the platform file. 

I am using SimDag - SimGrid 3.16 compiled with intel 2017 on CentOS operating system
I attached the code that reproduces the problem. 
build using "make"
run as  "./simulator platform.xml  12 1 1000 3"

[example.zip](https://github.com/simgrid/simgrid/files/1898086/example.zip)

**Comment by frs69wq** [comment] 2018-04-16 12:09
Could you please provide a **minimal** working example that reproduces the segmentation fault?  The 
current code is too complex to determine from where the issue could come.  

Could you also give us the backtrace produced by "valgrind ./simulator platform.xml 12 1 1000 3"?

thx

**Comment by aliomarabdelazim** [comment] 2018-04-16 17:48
Thank you very much for your reply. I stripped down the code more and attached the code. 
currently you can run as "./simulator platform.xml 12 1000"

Also I attached the valgrind backtrace of the execution  "valgrind ./simulator platform.xml 12 1000"

Please note that the same program binary would run perfectly if the platform is modified to comment out the configuration to use IB network model, the CPU model and compound host model. 

[example.zip](https://github.com/simgrid/simgrid/files/1916520/example.zip)

**Comment by mquinson** [comment] 2019-10-15 22:54
Hello, sorry for the very long delay for this answer.

I just tried to reproduce your problem, and it seems that it got fixed at some point, don't you think? You just have to kill the 2 first arguments of SD_dependency_add in the provided example, as they were removed in between.

I'm executing your code with either `./simulator platform.xml 12 1000 2` or `./simulator platform.xml 12 1 1000 3` and in both cases, the logs show that we are using the compound host model, but the simulation proceeds until its end.

```
$ ./simulator platform.xml 12 1 1000 3
[0.000000] [xbt_cfg/INFO] Configuration change: Set 'cpu/model' to 'Cas01'
[0.000000] [xbt_cfg/INFO] Configuration change: Set 'host/model' to 'compound'
[0.000000] [xbt_cfg/INFO] Configuration change: Set 'maxmin/precision' to '0.000000001'
[0.000000] [xbt_cfg/INFO] Configuration change: Set 'network/model' to 'IB'
[...]
rank 0 assigned from 0 to 1, chunk_size 1 
Experiment_parameters
Problem 1
Workers 12
-----------------------
Program time, 0.001418
$
```

@AOA-Mohammed can you confirm that this bug got fixed in between or can you still reproduce it? Again, I'm sorry for the delay.

**Comment by AOA-Mohammed** [comment] 2019-10-16 09:05
Thank you for your reply, I just tried today with SimGrid 3.22 and 3.23 and the segmentation fault is still there.

[0.000000] [xbt_cfg/INFO] Configuration change: Set 'host/model' to 'compound'
[0.000000] [xbt_cfg/INFO] Option smpi/bw_factor has been renamed to smpi/bw-factor. Consider switching.
[0.000000] [xbt_cfg/INFO] Configuration change: Set 'smpi/bw_factor' to '0:0.0321315259093186;4120:0.0876617184629479;17408:0.0806683186416976'
[0.000000] [xbt_cfg/INFO] Option smpi/bw_factor has been renamed to smpi/bw-factor. Consider switching.
[0.000000] [xbt_cfg/INFO] Configuration change: Set 'maxmin/precision' to '0.000000001'
[0.000000] [xbt_cfg/INFO] Configuration change: Set 'cpu/model' to 'Cas01'
[0.000000] [xbt_cfg/INFO] Configuration change: Set 'smpi/or' to '0:4.94519452542248e-07:5.21543502933321e-11;4120:3.87198789544124e-07:7.32656256820241e-11;17408:0:0'
[0.000000] [xbt_cfg/INFO] Configuration change: Set 'smpi/os' to '0:3.5355471684942e-07:1.20926287215865e-09;4120:3.25169405532333e-06:1.65966503731639e-10;17408:0:0'
[0.000000] [xbt_cfg/INFO] Configuration change: Set 'smpi/ois' to '0:8.82607235682149e-07:-2.33669764402541e-11;4120:-3.42779951158394e-06:6.82218034066036e-10;17408:0:0'
[0.000000] [xbt_cfg/INFO] Option smpi/send_is_detached_thres has been renamed to smpi/send-is-detached-thresh. Consider switching.
[0.000000] [xbt_cfg/INFO] Configuration change: Set 'smpi/send_is_detached_thres' to '2097152'
[0.000000] [xbt_cfg/INFO] Option smpi/send_is_detached_thres has been renamed to smpi/send-is-detached-thresh. Consider switching.
[0.000000] [xbt_cfg/INFO] Configuration change: Set 'smpi/iprobe' to '1.72822368421053e-07'
[0.000000] [xbt_cfg/INFO] Configuration change: Set 'smpi/wtime' to '3.784193e-08'
[0.000000] [xbt_cfg/INFO] Configuration change: Set 'network/model' to 'IB'
[0.000000] [xbt_cfg/INFO] Option smpi/async_small_thres has been renamed to smpi/async-small-thresh. Consider switching.
[0.000000] [xbt_cfg/INFO] Configuration change: Set 'smpi/async_small_thres' to '2097152'
[0.000000] [xbt_cfg/INFO] Option smpi/async_small_thres has been renamed to smpi/async-small-thresh. Consider switching.
[0.000000] [xbt_cfg/INFO] Option smpi/lat_factor has been renamed to smpi/lat-factor. Consider switching.
[0.000000] [xbt_cfg/INFO] Configuration change: Set 'smpi/lat_factor' to '0:11.3730903856856;4120:21.2824580159958;17408:140.467977690014'
[0.000000] [xbt_cfg/INFO] Option smpi/lat_factor has been renamed to smpi/lat-factor. Consider switching.
[0.000000] [xbt_cfg/INFO] Configuration change: Set 'smpi/test' to '4.27914285714286e-07'
rank 0 assigned from 0 to 1, chunk_size 1 
rank 1 assigned from 1 to 2, chunk_size 1 
rank 2 assigned from 2 to 3, chunk_size 1 
rank 3 assigned from 3 to 4, chunk_size 1 
rank 4 assigned from 4 to 5, chunk_size 1 
rank 5 assigned from 5 to 6, chunk_size 1 
rank 6 assigned from 6 to 7, chunk_size 1 
rank 7 assigned from 7 to 8, chunk_size 1 
rank 8 assigned from 8 to 9, chunk_size 1 
rank 9 assigned from 9 to 10, chunk_size 1 
rank 10 assigned from 10 to 11, chunk_size 1 
rank 11 assigned from 11 to 12, chunk_size 1 
Segmentation fault.
Segmentation fault (core dumped)

**Comment by mquinson** [comment] 2019-10-16 09:14
How do you start it? What is the exact command line to reproduce the bug?
Btw, I'm testing with 3.24, maybe that's the reason (even if I doubt it).

**Comment by AOA-Mohammed** [comment] 2019-10-16 09:17
./simulator platform.xml 12 1000, with the code attached
[example (2).zip](https://github.com/simgrid/simgrid/files/3733440/example.2.zip)

**Comment by mquinson** [comment] 2019-10-16 09:25
It works like a charm on SimGrid v3.24 released last week. You just have to kill the 2 first parameters to SD_task_dependency_add to make it compile.

Can you confirm?

**Comment by mquinson** [comment] 2019-10-16 09:28
If it also fails for you on 3.24, then it's maybe because you use a different compile-time configuration than I do. If so, I'd be interested in the result of `touch CMakeList.txt; cmake .` in your build tree.

**Comment by AOA-Mohammed** [comment] 2019-10-16 10:59
Yes, it failed also on 3.24. 

I am using easybuild to build and install SimGrid on our system. I attached the block I used to install SimGrid 3.24


[SimGrid-3.24-intel-2017a.eb.zip](https://github.com/simgrid/simgrid/files/3733889/SimGrid-3.24-intel-2017a.eb.zip)

**Comment by adegomme** [comment] 2019-10-16 11:14
Your eb configuration seems to download from https://gforge.inria.fr/frs/download.php/file/36900/ .. which is 3.16. It may just be renaming it to 3.24 later, but it's not 3.24.

3.23 is available on gforge, from https://gforge.inria.fr/frs/download.php/file/38069/SimGrid-3.23.tar.gz

We moved from gforge, so latest versions are pushed there only when we think about it ... You can download 3.24 from https://github.com/simgrid/simgrid/releases/download/v3.24/SimGrid-3.24.tar.gz

**Comment by mquinson** [comment] 2019-10-16 12:10
Woops, I just uploaded 3.24 to gforge:
https://gforge.inria.fr/frs/download.php/file/38173/SimGrid-3.24.tar.gz

**Comment by mquinson** [comment] 2019-10-16 14:19
if it's working with the latest version, then the bug is fixed :)

**Closed** 2019-10-16 15:08 UTC
Labels: moreinfo

**Comment by mquinson** [comment] 2019-10-16 15:18
@AOA-Mohammed : thanks for taking the time to investiguate this with us, despite the delay of our answer.

**Comment by AOA-Mohammed** [comment] 2019-10-16 15:21
Thanks for developing and supporting SimGrid. I am happy to know that the bug is now fixed as well.
