### ISSUE TITLE
Problems in simulating MPI_Send, MPI_Recv function

### ISSUE THREAD

**Issue by hibikid** [simgrid/simgrid#341] opened 2020-05-07 11:22 UTC
Hi,
I'm a user of Simgrid. I'm trying to simulate a simple MPI program as an accuracy test. Here is the code.  

```
#include "mpi.h"
#include <stdio.h>
#define MSG_SIZE 262144*64 //(64MB)

int main(int argc, char *argv[])
{
    int rank,size,i;
    int *a=new int[MSG_SIZE];
    int *recvtemp=new int[MSG_SIZE];
    double time1,time2;

    MPI_Status status;
    MPI_Init(&argc,&argv);
    MPI_Comm_size(MPI_COMM_WORLD,&size);
    MPI_Comm_rank(MPI_COMM_WORLD,&rank);

    for(i=0;i<MSG_SIZE;i++)
        a[i]=1;

    time1=MPI_Wtime();
    for(i=0;i<100;i++){
        if (rank == 0)
            MPI_Send(a,MSG_SIZE,MPI_INT,1,i,MPI_COMM_WORLD);
        else
            MPI_Recv(recvtemp,MSG_SIZE,MPI_INT,0,i,MPI_COMM_WORLD,&status);
    }
    time2=MPI_Wtime();

    if(rank==0){
        printf("sendtime:%f\n",time2-time1);
    }
    MPI_Finalize();
}
```
I ran this code on our cluster with Open MPI 3.1.2, the command is:
> mpirun -np 2 -H gpu13,gpu14 /PATH/mpi_test_code  

Our cluster's setup is a switch connects each node with links which bandwidth is 10Gbps. And the output is:
>[cryang99@gpu13 ~]$ mpirun -np 2 -H gpu13,gpu14 mpitest/mpisize-test
sendtime:12.201367  

Then, I use Simgrid on my PC with following setting (cluster_crossbar.xml and  cluster_hostfile) :
```
<?xml version='1.0'?>
<!DOCTYPE platform SYSTEM "http://simgrid.gforge.inria.fr/simgrid/simgrid.dtd">
<platform version="4.1">
  <!--           _________
                |          |
                | crossbar |
                |__________|
                    / | \
                   /  |  \
               l0 / l1|   \l2
                 /    |    \
                /     |     \
           node-0   node-1   node-2 ...

    All hosts can communicate at full speed with no interference on
    the crossbar. Only the links of each hosts are limiting.
  -->
  <zone id="world" routing="Full">
    <cluster id="cluster-crossbar"
             prefix="node-" radical="0-100" suffix=".simgrid.org"
             speed="1000Gf" bw="10Gbps" lat="25us"/>
  </zone>
</platform>
```
```
node-0.simgrid.org
node-1.simgrid.org
```
The command is:
>smpirun -np 2 -platform cluster_crossbar.xml -hostfile cluster_hostfile --cfg=smpi/display-timing:yes --cfg=smpi/host-speed:72380000000 ./msgsize_test  

The output is:
>[0.000000] [xbt_cfg/INFO] Configuration change: Set 'surf/precision' to '1e-9'
[0.000000] [xbt_cfg/INFO] Configuration change: Set 'network/model' to 'SMPI'
[0.000000] [xbt_cfg/INFO] Configuration change: Set 'smpi/display-timing' to 'yes'
[0.000000] [xbt_cfg/INFO] Configuration change: Set 'smpi/host-speed' to '72380000000'
sendtime:5.765397
[11.536449] [smpi_kernel/INFO] Simulated time: 11.5364 seconds.
The simulation took 1.40616 seconds (after parsing and platform setup)
0.15625 seconds were actual computation of the application  

There are two points bothers me: 1. The sendtime is quite different (12.2s and 5.8s). 2. The simgrid says that the simulated time is 11.5s but the sendtime is olny 5.8s. In my code the rest of time is just generating the message and init the MPI processes which could be done on cluster within 0.15s.
Also I use ***ifstat*** to observe the bandwidth when running on cluster:
on ***gpu13***:
>    ens14f1       
KB/s in  KB/s out 
   0.06      0.00 
   0.00      0.00 
   0.00      0.00 
   0.00      0.00 
   0.00      0.00 
   0.06      0.00 
   0.00      0.00 
   0.00      0.00 
   0.00      0.00 
   0.00      0.00 
   0.06      0.00 
   0.00      0.00 
   0.00      0.00 
 114.49  77831.99 
 828.88  447176.7 
1018.98  511793.5 
1107.74  531151.0 
1379.53  637959.3 
1043.05  553997.9 
1053.65  543040.3 
1296.58  625226.6 
 961.05  498498.8 
 892.10  486580.1 
1104.07  539253.6 
1413.94  639539.1 
1160.79  608648.3 
 272.16  160443.3 

The max bandwidth used is about 6Gbps. (Use ***iperf*** could get 10Gbps as the max available band width).  

I‘m quite unsure why these happened, is there some wrong setting in Simgrid or I'd better try Simgrid on a single node in our cluster?  
Any of your reply is appreciated！

**Comment by adegomme** [comment] 2020-05-07 12:10
Hi,
well, as you say, your real platform does not reach 10Gbps (that's expected), so if you say to simgrid to use 10Gps links, simgrid will report shorter times than reality.

You're sending 100*64MiB, so 53Gb on a 10Gbps network -> 5.3s, close to the 5.7 reported by simgrid (which includes latency and some other small effects).
Your network being actually slower, it takes more time (as you saw, your peak is 6Gbps, but the mean appears to be less).
, 
One (not great) solution is to report only 5 or 6Gbps in your platform file, one better is to look at platform calibration ( https://framagit.org/simgrid/platform-calibration/ even if I'm not sure it's currently usable as is) to perform some standardized experiments which will then report corrective factors to give to simgrid to account for real platform behavior for various message sizes.

For the second point, I can't reproduce here :
sendtime:5.765421
[5.769596] [smpi_kernel/INFO] Simulated time: 5.7696 seconds.

It looks like a discrepancy between the host-speed you report (72Gf) and the speed of the node (1000Gf). Was it indeed set to 1000Gf for your run ? 
If it was, please send the smpi_simgrid.trace generated by adding " -trace --cfg=tracing/smpi/computing:1 " to the run.

Whih version of simgrid are you using ?

**Comment by hibikid** [comment] 2020-05-07 12:47
The version of simgrid is 3.18.
I added " -trace --cfg=tracing/smpi/computing:1 " and rerun the cmd, here is the output and tracefile.
>[0.000000] [xbt_cfg/INFO] Configuration change: Set 'tracing' to 'yes'
[0.000000] [xbt_cfg/INFO] Configuration change: Set 'tracing/filename' to 'smpi_simgrid.trace'
[0.000000] [xbt_cfg/INFO] Configuration change: Set 'tracing/smpi' to 'yes'
[0.000000] [xbt_cfg/INFO] Configuration change: Set 'surf/precision' to '1e-9'
[0.000000] [xbt_cfg/INFO] Configuration change: Set 'network/model' to 'SMPI'
[0.000000] [xbt_cfg/INFO] Configuration change: Set 'smpi/display-timing' to 'yes'
[0.000000] [xbt_cfg/INFO] Configuration change: Set 'smpi/host-speed' to '72380000000'
[0.000000] [xbt_cfg/INFO] Configuration change: Set 'tracing/smpi/computing' to '1'
sendtime:5.765397
[11.536449] [smpi_kernel/INFO] Simulated time: 11.5364 seconds.
The simulation took 1.41203 seconds (after parsing and platform setup)
0.140625 seconds were actual computation of the application


[smpi_simgrid.trace.txt](https://github.com/simgrid/simgrid/files/4592927/smpi_simgrid.trace.txt)
as ***.trace*** can't upload, ***.txt*** is added.

**Comment by adegomme** [comment] 2020-05-07 12:56
grep -c PTP ../smpi_simgrid.trace.txt
400

that's 400 start/end of messages, so 200 messages exchanged, so you're not executing the code you sent me, I would say .

 grep -c PTP ./smpi_simgrid.trace
200
on mine.

ps: 3.18 is quite outdated now, you should move to a more recent one (last is 3.25). If you're on ubuntu 18.04, 20.04 has been released recently and has 3.24. 
Installing from sources is an alternative.

**Comment by hibikid** [comment] 2020-05-07 13:13
yep, as you mentioned
I found that in other binary which name nearly same as the name I ran before is the real could expected to run.  
I may use the wrong logged command.
now everything is ok!
>[0.000000] [xbt_cfg/INFO] Configuration change: Set 'tracing' to 'yes'
[0.000000] [xbt_cfg/INFO] Configuration change: Set 'tracing/filename' to 'smpi_simgrid.trace'
[0.000000] [xbt_cfg/INFO] Configuration change: Set 'tracing/smpi' to 'yes'
[0.000000] [xbt_cfg/INFO] Configuration change: Set 'surf/precision' to '1e-9'
[0.000000] [xbt_cfg/INFO] Configuration change: Set 'network/model' to 'SMPI'
[0.000000] [xbt_cfg/INFO] Configuration change: Set 'smpi/display-timing' to 'yes'
[0.000000] [xbt_cfg/INFO] Configuration change: Set 'smpi/host-speed' to '72380000000'
[0.000000] [xbt_cfg/INFO] Configuration change: Set 'tracing/smpi/computing' to '1'
sendtime:5.765397
[5.771052] [smpi_kernel/INFO] Simulated time: 5.77105 seconds.

I'm going to check out the platform calibration.

**Comment by mquinson** [comment] 2020-05-10 12:24
Closing now since @hibikid reported that everything is now OK.
Thanks for reporting, and feel free to reopen, or open another bug, if any problem resurfaces.

**Closed by mquinson** 2020-05-10 12:24 UTC
